(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }})("map1",
{ "height":9,
 "layers":[
        {
         "data":[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         "height":9,
         "name":"Kachelebene 1",
         "offsetx":-0.5,
         "offsety":-0.5,
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":11,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "height":9,
         "name":"Objektebene 1",
         "objects":[
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":1,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":2,
                 "y":1
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":1,
                 "y":2
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":4,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":2,
                 "y":3
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":5,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":3,
                 "y":2
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":14,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":2.00555555555556,
                 "y":4.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":15,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":2.00555555555556,
                 "y":6.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":16,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":1.00555555555556,
                 "y":5.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":17,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":3.00555555555556,
                 "y":5.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":18,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":4.99444444444445,
                 "y":5.00555555555556
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":19,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":4.99444444444445,
                 "y":7.00555555555556
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":20,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":3.99444444444444,
                 "y":6.00555555555556
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":21,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":5.99444444444445,
                 "y":6.00555555555556
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":22,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":7.99444444444445,
                 "y":5.01666666666667
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":23,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":7.99444444444445,
                 "y":7.01666666666667
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":24,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":6.99444444444445,
                 "y":6.01666666666667
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":25,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":8.99444444444445,
                 "y":6.01666666666667
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":26,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":7.99444444444445,
                 "y":0.994444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":27,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":7.99444444444445,
                 "y":2.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":28,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":6.99444444444445,
                 "y":1.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":29,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":8.99444444444445,
                 "y":1.99444444444444
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":30,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":4.98333333333333,
                 "y":0.983333333333334
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":31,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":4.98333333333333,
                 "y":2.98333333333333
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":3.98333333333333,
                 "y":1.98333333333333
                }, 
                {
                 "ellipse":true,
                 "height":0.5,
                 "id":33,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0.5,
                 "x":5.98333333333333,
                 "y":1.98333333333333
                }],
         "offsetx":-0.25,
         "offsety":-0.25,
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":11,
         "x":0,
         "y":0
        }],
 "nextobjectid":35,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":1,
 "tilesets":[
        {
         "columns":4,
         "firstgid":1,
         "image":"..\/..\/asset-source\/pseudo-tile-set.png",
         "imageheight":1,
         "imagewidth":4,
         "margin":0,
         "name":"Pseudo",
         "properties":
            {

            },
         "spacing":0,
         "tilecount":4,
         "tileheight":1,
         "tilewidth":1
        }],
 "tilewidth":1,
 "version":1,
 "width":11
});